all: quadraticroots

quadraticroots: main.o quadraticroots.o
    gcc main.o quadraticroots.o -o quadraticroots -lm

main.o: mian.c quadraticroots.h
    gcc -c main.c

quadraticroots.o: quadraticroots.c quadraticroots.h
    gcc -c quadraticroots.c

clean:
    -rm -f *.o *.exe